name: eksCordon tests
on:
  push:
    #paths:
    #  - 'eksMgnt/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: run go tests
        run: |
          mkdir -p /home/runner/.kube
          cat config-test
          cat config-test > ${HOME}/.kube/config
          go test -v ./...
