name: eksCordon tests
on:
  push:
    #paths:
    #  - 'eksMgnt/**'
jobs:
  test:
    strategy:
      matrix:
        go-versions: [1.15.x, 1.16.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up go version
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-versions }}
      - name: run go tests
        run: |
          mkdir -p /home/runner/.kube
          cat config-test > ${HOME}/.kube/config
          go test -v ./...
