name: eksMgnt tests
on:
  push:
    paths:
      - 'eksMgnt/**'
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: use go version
        uses: actions/setup-go@2
        with:
          go-version: ${{ matrix.go-version }}
        run: |
          cd eksMgnt
          go test -v ./...
