name: eksCordon tests
on:
  push:
    #paths:
    #  - 'eksMgnt/**'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-versions: [1.15.x, 1.16.x]
          #os: [ubuntu-latest, macos-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up go version
        with:
          go-version: ${{ matrix.go-versions }}
          
      - name: run go tests
        run: |
          mkdir -p /home/runner/.kube
          cat config-test > ${HOME}/.kube/config
          go test -v ./...
